feat: support policy evaluation
PKU-MARL/omnisafe pull request #137
Opened 2023-03-07 16:06 UTC by Gaiejj

## Description

feat: support policy evaluation

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [ ] I have ensured `make test` pass. (**required**)

2023-03-08 16:56 UTC, zmsn-2077 commented on omnisafe/common/normalizer.py
>  """Implementation of Vector Buffer."""
Vector Buffer should not appear in this file.

2023-03-08 16:57 UTC, zmsn-2077 commented on omnisafe/evaluator.py
>          Args:
I think the `Args` in the comment do not match the real function arguments.

2023-03-08 16:58 UTC, zmsn-2077 commented on omnisafe/evaluator.py
> +            save_dir (str): directory where the model is saved.
the same problems

2023-03-08 16:59 UTC, zmsn-2077 commented on omnisafe/evaluator.py
> +            episode_rewards (list): list of episode rewards.
need to fix,
        ```
        return (
            episode_rewards,
            episode_costs,
        )
        ```

2023-03-08 16:59 UTC, zmsn-2077 requested changes
.

2023-03-09 16:55 UTC, rockmagma02 approved these changes

2023-03-10 05:06 UTC, zmsn-2077 approved these changes
LGTM.

2023-03-10 05:07 UTC, merged