refactor(wrapper): refactor the cuda setting
PKU-MARL/omnisafe pull request #176
Opened 2023-03-25 08:10 UTC by Gaiejj

## Description

refactor the cuda setting

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-03-25 14:02 UTC, rockmagma02 commented on omnisafe/adapter/offpolicy_adapter.py
>              next_obs, reward, cost, terminated, truncated, info = self.step(act)
in all loop of `roll_out_step`, use same `act`? it seem like a bug, we must consider the situation `roll_out_step` != 1

2023-03-25 14:16 UTC, rockmagma02 requested changes

2023-03-25 14:16 UTC, rockmagma02 commented on omnisafe/envs/safety_gymnasium_env.py
> +        obs, reward, cost, terminated, truncated, info = self._env.step(action.cpu().numpy())
use `action.detach().cpu().numpy()`

2023-03-25 14:16 UTC, rockmagma02 commented on omnisafe/envs/core.py
> +        return (
change device only in `safety_gymnasium_env.py` please, changing device in `Wrapper` could cause multi-calculating in `reset` and `step`

2023-03-26 13:36 UTC, rockmagma02 requested changes

2023-03-26 13:36 UTC, rockmagma02 commented on omnisafe/envs/safety_gymnasium_env.py
> +        self, env_id: str, num_envs: int = 1, device: torch.device = 'cpu', **kwargs
`device: torch.device = torch.device('cpu')`

2023-03-26 13:44 UTC, rockmagma02 approved these changes

2023-03-26 17:30 UTC, zmsn-2077 approved these changes
LGTM.

2023-03-26 17:31 UTC, merged