docs: fix spelling error
PKU-MARL/omnisafe pull request #56
Opened 2022-12-24 03:20 UTC by Gaiejj

## Description

docs: fix spelling error

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/PKU-MARL/omnisafe/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2022-12-24 08:48 UTC, XuehaiPan commented on README.md
Install VS Code extension _Markdown All in One_ and regenerate this TOC.

2022-12-24 08:50 UTC, XuehaiPan commented on docs/source/conf.py
> +extensions = ['recommonmark', 'sphinx_markdown_tables', 'sphinx_design', 'sphinx_copybutton']
Revert this file.

2022-12-24 08:51 UTC, XuehaiPan commented on docs/source/spelling_wordlist.txt
> +bool
Revert changes in this file above.

2022-12-24 08:54 UTC, XuehaiPan commented on docs/source/spelling_wordlist.txt
> +neighbourhood
Use American English to fit the en-US dictionary.

2022-12-24 08:55 UTC, XuehaiPan requested changes
Enable spelling check in the `lint` target in `Makefile` and enable `make spelling` in GitHub Action workflows.

2022-12-24 10:24 UTC, XuehaiPan approved these changes

2022-12-25 10:33 UTC, zmsn-2077 approved these changes

2022-12-25 10:35 UTC, merged