refactor(off_policy): change args passing
PKU-MARL/omnisafe pull request #58
Opened 2022-12-24 15:28 UTC by Gaiejj

## Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/PKU-MARL/omnisafe/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2022-12-25 10:35 UTC, zmsn-2077 approved these changes
After careful review, I agree with these changes.

2022-12-25 10:36 UTC, XuehaiPan requested changes
Rebase changes.

2022-12-26 13:13 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +
Use items and remove the empty lines:

```text
    References:

        - Title: Continuous control with deep reinforcement learning
        - Authors: Timothy P. Lillicrap, Jonathan J. Hunt, Alexander Pritzel, Nicolas Heess, Tom Erez,
                   Yuval Tassa, David Silver, Daan Wierstra.
        - URL: https://arxiv.org/abs/1509.02971
```

2022-12-26 13:14 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
>  import time
An empty line before imports.

2022-12-26 13:14 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +    # pylint: disable=too-many-arguments
Use `pylint: disable-next`, the same changes for all other comments.

2022-12-26 13:15 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +            done (:class:`torch.Tensor`): :meth:`terminated` saved in data.
```suggestion
            obs (:class:`torch.Tensor`): ``observation`` saved in data.
            act (:class:`torch.Tensor`): ``action`` saved in data.
            rew (:class:`torch.Tensor`): ``reward`` saved in data.
            obs_next (:class:`torch.Tensor`): ``next observations`` saved in data.
            done (:class:`torch.Tensor`): ``terminated`` saved in data.
```

2022-12-26 13:18 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +        #.  Update target net by :func:`polyak_update_target()`
1. A extra line before the description.
2. Use `:meth:` without brackets.

```suggestion

        Update step contains three parts:

        #.  Update value net by :meth:`update_value_net`
        #.  Update cost net by :meth:`update_cost_net`
        #.  Update policy net by :meth:`update_policy_net`
        #.  Update target net by :meth:`polyak_update_target`
```

2022-12-26 13:19 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/sac.py
> +    # pylint: disable=too-many-locals, disable=too-many-arguments
```suggestion
    # pylint: disable-next=too-many-locals,too-many-arguments
```

2022-12-26 13:20 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/sac.py
> +            :class: hint
```suggestion
        .. hint::
```

2022-12-28 08:55 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +            obs_next (:class:`torch.Tensor`): ``net observation`` saved in data.
```suggestion
            obs_next (:class:`torch.Tensor`): ``next observation`` saved in data.
```

2022-12-28 08:56 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +        #.  Update target net by :meth:`polyak_update_target()`
```suggestion
        Update step contains three parts:

        #.  Update value net by :meth:`update_value_net`
        #.  Update cost net by :meth:`update_cost_net`
        #.  Update policy net by :meth:`update_policy_net`
        #.  Update target net by :meth:`polyak_update_target`
```

No brackets.

2022-12-28 08:56 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/ddpg.py
> +        #.  Update target net by :meth:`polyak_update_target()`
```suggestion
        Update step contains three parts:

        #.  Update value net by :meth:`update_value_net`
        #.  Update cost net by :meth:`update_cost_net`
        #.  Update policy net by :meth:`update_policy_net`
        #.  Update target net by :meth:`polyak_update_target`
```

No brackets.

2022-12-28 08:57 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/sddpg.py
> +                Mohammad Ghavamzadeh.
```suggestion
        - Authors: Yinlam Chow, Ofir Nachum, Aleksandra Faust, Edgar Duenez-Guzman,
                    Mohammad Ghavamzadeh.
```

2022-12-28 08:57 UTC, XuehaiPan commented on omnisafe/algorithms/off_policy/sddpg.py
> +                Mohammad Ghavamzadeh.
```suggestion
        - Authors: Yinlam Chow, Ofir Nachum, Aleksandra Faust, Edgar Duenez-Guzman,
                   Mohammad Ghavamzadeh.
```

2023-01-03 15:32 UTC, closed without merging