feat: support auto render as .mp4 videos, add examples and tests.
PKU-MARL/omnisafe pull request #60
Opened 2022-12-25 07:24 UTC by muchvo

## Description

1.Support directly render on server and save episodes as .mp4 videos.
2.Add new tests.
3.Add examples to show how to use.
4.Update some wrappers.
5.After carefully testing.
![image](https://user-images.githubusercontent.com/118189931/209460022-4795a449-7da2-415c-8659-ba449127de62.png)

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/PKU-MARL/omnisafe/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format`. (**required**)
- [ ] I have checked the code using `make lint`. (**required**)
- [ ] I have ensured `make test` pass. (**required**)

2022-12-25 10:41 UTC, zmsn-2077 commented on envs/safety-gymnasium/setup.py
> +#!/usr/bin/env python3
why do we need to add this line?

2022-12-25 10:43 UTC, zmsn-2077 commented on .github/workflows/ci.yml
> +      - name: Install safety_gymnasium
Why is this part modified? Does it need to be updated with the main branch?

2022-12-25 10:48 UTC, zmsn-2077 requested changes
.

2022-12-25 13:07 UTC, zmsn-2077 approved these changes
After careful review, I agree with these changes.

2022-12-26 12:13 UTC, calico-1226 approved these changes
I approve these changes.

2022-12-27 11:23 UTC, merged