fix: fix distributed tool
PKU-MARL/omnisafe pull request #63
Opened 2023-01-01 04:29 UTC by Gaiejj

## Description

fix: fix distributed tool

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-01-01 15:06 UTC, zmsn-2077 submitted a review, later dismissed

2023-01-02 08:25 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
> +def mpi_statistics_scalar(value: torch.Tensor, with_min_and_max=False) -> tuple:
```suggestion
def mpi_statistics_scalar(value: torch.Tensor, with_min_and_max: bool = False) -> Union[Tuple[np.ndarray, np.ndarray], Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
```

2023-01-02 08:26 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
>  def sync_params(module):
```suggestion
def sync_params(module: torch.nn.Module) -> None:
```

2023-01-02 08:27 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
> +    """Judge whether the process is the root process."""
```suggestion
    """Test whether the process is the root process."""
```

2023-01-02 14:32 UTC, XuehaiPan requested changes
Regenerate TOC.

2023-01-02 14:33 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
> +    Input is a 1D array of size N, and output is a list of size N * MPI_world_size.
```suggestion
    Input is a 1D array of size ``N``, and output is a list of size ``N * MPI_world_size``.
```

2023-01-02 14:33 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
>      """Gather values from all tasks and return flattened list.
```suggestion
    """Gather values from all tasks and return a flattened list.
```

2023-01-03 12:56 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
> +        Usage: if ``mpi_fork(n)`` : ``sys.exit()``
```suggestion
    Examples:
        .. code-block:: python

            if mpi_fork(n):  # forks the current script and calls MPI
                sys.exit()   # exit single thread python process
```

2023-01-03 12:57 UTC, XuehaiPan requested changes
Please fix the TOC in README.

2023-01-03 12:59 UTC, XuehaiPan commented on omnisafe/utils/distributed_utils.py
> +    scalars must be assigned.
Wrap the docstrings at a specific column (e.g., at 100 characters per line).

2023-01-03 16:13 UTC, closed without merging