refactor: change wrapper setting
PKU-MARL/omnisafe pull request #73
Opened 2023-01-11 04:00 UTC by Gaiejj

## Description

refactor: change wrapper setting

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/PKU-MARL/omnisafe/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://omnisafe.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-01-11 06:05 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/ddpg.py
> -
This blank line is required.

2023-01-11 06:18 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/ddpg_lag.py
duplicate line, one blank line.

2023-01-11 06:20 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/sac.py
>  """Implementation of the SAC algorithm."""
blank line.

2023-01-11 06:21 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/sac_lag.py
>  """Implementation of the Lagrange version of the SAC algorithm."""
blank line.

2023-01-11 06:24 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/sddpg.py
> +from typing import Dict, NamedTuple, Tuple
blank line.

2023-01-11 06:24 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/td3.py
>  """Implementation of the TD3 algorithm."""
blank line.

2023-01-11 06:25 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/td3_lag.py
>  """Implementation of the Lagrange version of the TD3 algorithm."""
blank line.

2023-01-11 06:27 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/early_terminated/ppo_early_terminated.py
>          URL: https://arxiv.org/abs/2107.04200
why is this line different from Reference's comment in off-policy algorithms?

2023-01-11 06:32 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/first_order/focops.py
> +    # pylint: disable=too-many-locals
should we use disable？

2023-01-11 06:34 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/naive_lagrange/ppo_lag.py
Do I need to cite the safety gym paper here?

2023-01-11 06:35 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/cpo.py
> +        - URL: https://arxiv.org/abs/1705.10528
URL style.

2023-01-11 06:36 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/pcpo.py
>          URL: https://arxiv.org/abs/2010.03152
URL styple.

2023-01-11 06:38 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/pcpo.py
> +    # pylint: disable=too-many-locals,invalid-name,too-many-arguments
disable-next

2023-01-11 07:16 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/pcpo.py
>          # Train policy with multiple steps of gradient descent
Lowercase

2023-01-11 07:16 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/pcpo.py
> +        # Compute the loss of policy net.
Lowercase

2023-01-11 07:16 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/second_order/pcpo.py
> +        # Process the advantage function.
Lowercase

2023-01-11 08:16 UTC, zmsn-2077 commented on omnisafe/common/normalize.py
> +        """FOrward"""
error spelling

2023-01-11 08:26 UTC, zmsn-2077 commented on omnisafe/wrappers/cmdp_wrapper.py
> +                # Only save EpRet / EpLen if trajectory finished
delete this line？

2023-01-11 08:27 UTC, zmsn-2077 commented on omnisafe/wrappers/cmdp_wrapper.py
> +            # pylint: disable=unused-variable
disable

2023-01-11 08:29 UTC, zmsn-2077 commented on omnisafe/wrappers/early_terminated_wrapper.py
> +class EarlyTerminatedWrapper(CMDPWrapper):  # pylint: disable=too-many-instance-attributes
disable

2023-01-11 08:32 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/td3_lag.py
>  class TD3Lag(TD3, Lagrange):  # pylint: disable=too-many-instance-attributes
disable

2023-01-11 08:32 UTC, zmsn-2077 commented on omnisafe/algorithms/off_policy/td3_lag.py
>      """The Lagrange version of the TD3 algorithm
.

2023-01-11 08:33 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/pid_lagrange/trpo_pid.py
> +    # pylint: disable=too-many-arguments
disable

2023-01-11 08:33 UTC, zmsn-2077 commented on omnisafe/algorithms/on_policy/base/ppo.py
> +    # pylint: disable=too-many-arguments
disable

2023-01-11 09:10 UTC, zmsn-2077 requested changes
.

2023-01-12 06:32 UTC, calico-1226 approved these changes
I approve these changes.

2023-01-12 08:07 UTC, merged